# Generated by Django 4.2.7 on 2023-12-15 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='savers',
        ),
    ]
